import React from 'react'
import s from './help.module.css'

const Help = () => (
    <div className={s.help}>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam finibus lacus facilisis sem auctor, et condimentum lacus fringilla. Proin pulvinar mattis sem a vestibulum. Praesent semper eget erat consequat convallis. Phasellus posuere ultricies tristique. Donec volutpat turpis vel velit ultrices, eget ullamcorper tellus pharetra. Curabitur dapibus lectus at enim fermentum, in feugiat ipsum malesuada. Vestibulum mollis, orci eu tincidunt pharetra, ligula elit dignissim sapien, at aliquet odio erat nec libero. Sed a gravida felis. Aliquam erat volutpat. Donec porttitor orci magna, sed lobortis lectus iaculis vitae. Nullam felis lectus, ornare quis ante vel, dictum pharetra metus. Praesent pulvinar, urna at vehicula finibus, mauris ligula dictum ligula, at commodo libero dui at urna. Nulla facilisi. Ut fermentum metus eget auctor vulputate.</p>
        <p>Morbi porta in enim sit amet tincidunt. Vivamus elementum eu lorem ut tincidunt. Nunc lacinia bibendum metus at finibus. Phasellus elit dui, semper quis lorem non, ornare porttitor urna. Nulla aliquet convallis nisl at euismod. Donec vel volutpat urna. Nunc sagittis nisl leo, eget tempus turpis malesuada id.</p>
        <p>Aliquam varius varius velit eu varius. Sed varius nec risus sit amet vehicula. Nullam auctor mi varius, lacinia lacus a, bibendum sapien. Quisque tincidunt urna purus, sit amet auctor libero aliquam posuere. Cras ut efficitur massa. Donec ultrices tincidunt dolor, nec sollicitudin nulla elementum non. Donec a pharetra ligula, at consectetur elit. Aliquam viverra ante ac erat venenatis, eu auctor tellus faucibus. Nunc eleifend dolor nec risus suscipit, vitae sodales odio sodales. Suspendisse potenti.</p>
        <p>Sed malesuada feugiat quam vitae blandit. Sed vel tellus et felis feugiat efficitur ac a turpis. Aenean rutrum gravida risus, vestibulum cursus eros aliquam a. Aliquam interdum justo lacus, a dignissim mauris pharetra et. In ex neque, dapibus sed commodo nec, ultricies at lorem. Sed ut tempor sapien. Sed feugiat, turpis sed malesuada hendrerit, augue risus varius erat, eget dapibus eros nisi non nisl. Pellentesque nec justo a turpis lobortis dignissim quis non nibh. Phasellus posuere pellentesque libero ac pharetra. Ut et tellus ullamcorper, ultricies metus et, pulvinar felis. Sed id rutrum nunc, eget eleifend purus. Morbi non tincidunt dolor. Aliquam fringilla sem sit amet dui dapibus, in pellentesque felis vehicula. Pellentesque ut lectus et libero fermentum finibus eget vel nulla. Cras consequat diam et magna ultricies, id ultricies diam pharetra.</p>
        <p>Maecenas arcu mauris, convallis maximus dui a, venenatis viverra orci. Donec pretium libero eget tellus pellentesque, elementum efficitur dolor mollis. Praesent sed malesuada libero. Vestibulum commodo ante ut mi blandit, vel facilisis nulla facilisis. Vivamus a dui eget sem lacinia eleifend. Cras scelerisque porta sem a venenatis. Vivamus accumsan eu eros commodo rutrum. In auctor, enim pretium semper rhoncus, tellus felis condimentum justo, vitae tincidunt est neque ut nulla. Mauris id turpis pharetra turpis convallis volutpat.</p>
    </div>
);

export default Help