export const GET_ALL_QUIZZES_START = 'GET_ALL_QUIZZES_START';
export const GET_ALL_QUIZZES_SUCCESS = 'GET_ALL_QUIZZES_SUCCESS';
export const GET_ALL_QUIZZES_ERROR = 'GET_ALL_QUIZZES_ERROR';

export const GET_QUIZ_START = 'GET_QUIZ_START';
export const GET_QUIZ_SUCCESS = 'GET_QUIZ_SUCCESS';
export const GET_QUIZ_ERROR = 'GET_QUIZ_ERROR';

export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const ADD_QUIZ = 'ADD_QUIZ';
export const DELETE_QUIZ = 'DELETE_QUIZ';